//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advent.Solutions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Advent.Solutions.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1837
        ///1585
        ///1894
        ///1715
        ///1947
        ///1603
        ///1746
        ///1911
        ///1939
        ///1791
        ///1800
        ///1479
        ///1138
        ///1810
        ///1931
        ///1833
        ///1470
        ///1882
        ///1725
        ///1496
        ///1890
        ///1862
        ///1990
        ///1958
        ///1997
        ///1844
        ///1524
        ///541
        ///2001
        ///1591
        ///1687
        ///1941
        ///1940
        ///1561
        ///1813
        ///1654
        ///1500
        ///1575
        ///1826
        ///2006
        ///679
        ///1660
        ///1679
        ///1631
        ///2008
        ///575
        ///1583
        ///1883
        ///1904
        ///1436
        ///1650
        ///1532
        ///1907
        ///1803
        ///1693
        ///1700
        ///359
        ///1516
        ///1625
        ///1908
        ///1994
        ///1910
        ///1644
        ///1706
        ///1781
        ///1639
        ///1662
        ///1712
        ///1796
        ///1915
        ///1550
        ///1721
        ///1697
        ///1917
        ///1665
        ///1646
        ///1968
        ///1881
        ///1893
        ///1468
        ///1678
        ///1774
        ///285
        ///1754
        ///1856
        ///1677
        ///1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day1Input {
            get {
                return ResourceManager.GetString("Day1Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 17-19 p: pwpzpfbrcpppjppbmppp
        ///10-11 b: bbbbbbbbbbbj
        ///17-19 c: ccccccccccfrcctcccjc
        ///8-10 k: kkkkkkkfkkks
        ///13-14 l: lvllvllllslllv
        ///8-9 n: nhhcnnnknnqnb
        ///1-3 d: pdbdfbws
        ///5-6 v: vvvgvb
        ///7-8 x: gxcxtwbl
        ///2-15 r: xlgrwqpcsqtrvfrrt
        ///9-14 l: glnldlllllllln
        ///2-3 r: vxnw
        ///8-9 g: gfggczgkgggjgg
        ///4-5 d: ddddh
        ///6-9 t: zttttbhbttttftd
        ///3-6 k: kkkzwnmv
        ///2-7 w: sgmvplwwjx
        ///11-13 h: hhhvhhhhhhvhh
        ///9-10 f: mhfdfffffmlffsfvts
        ///17-18 l: llllllllllllllllrzl
        ///4-5 c: crcccccccvc
        ///9-12 q: qqqqqpqrqqlcq
        ///7-8 n: nnnnnndn
        ///3-5 f: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day2Input {
            get {
                return ResourceManager.GetString("Day2Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .#.....#..#..#....##.........#.
        ///...#...#.........#..#.#..#.....
        ///#.#...#.#....#.....#..#..##..##
        ///..#..#.#.#.....#..#..#..##.....
        ///.#..........#....####..##.#..#.
        ///....##.......#.#.....#.........
        ///....#......#....####.#.##......
        ///........##..........##......#..
        ///.........#........##..#.#.....#
        ///.#..##..........#..#...#..##.#.
        ///........#........#.....#....#.#
        ///..#.......#.###...#.......##...
        ///.##..##.#...#........#.........
        ///...#....#..#..#..##.......#..#.
        ///.#.#.##.##..##..#.#.....#.....#
        ///....#.........#.. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day3Input {
            get {
                return ResourceManager.GetString("Day3Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to byr:2010 pid:#1bb4d8 eyr:2021 hgt:186cm iyr:2020 ecl:grt
        ///
        ///pid:937877382 eyr:2029
        ///ecl:amb hgt:187cm iyr:2019
        ///byr:1933 hcl:#888785
        ///
        ///ecl:hzl
        ///eyr:2020
        ///hcl:#18171d
        ///iyr:2019 hgt:183cm
        ///byr:1935
        ///
        ///hcl:#7d3b0c hgt:183cm cid:135
        ///byr:1992 eyr:2024 iyr:2013 pid:138000309
        ///ecl:oth
        ///
        ///ecl:hzl
        ///hgt:176cm pid:346059944 byr:1929 cid:150 eyr:1924 hcl:#fffffd iyr:2016
        ///
        ///iyr:2011
        ///cid:99 ecl:amb
        ///eyr:2030 hcl:#18171d
        ///hgt:165cm pid:897123249 byr:1948
        ///
        ///hcl:#cfa07d pid:827609097 ecl:gry iyr:2017 byr:1963
        ///eyr:2029 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day4Input {
            get {
                return ResourceManager.GetString("Day4Input", resourceCulture);
            }
        }
    }
}
